Add different styles
ThumbWorks/sf-ios pull request #111
Opened 2019-05-19 17:53 UTC by zadr

Add support for changing the style in the app, where style is defined by a unified set of fonts + colors picked from a central location.

PR is kinda big, but, basically all the work is in one of two categories:
1. plumbing to get the `Style` object available everywhere it needed to be
2. removing `UIFont` and `UIColor` calls in favor of asking the style for a value to use

I started with three styles, Affogato (classic look), Espresso (a nice dark brown look) and Cherry Mocha (dark mode), but I'm not attached to any of these looks and we should change 'em around as needed to look dope.

Screenshots:

**Affogato**
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 28](https://user-images.githubusercontent.com/128868/57985921-b031ab80-7a23-11e9-80dd-6a100f469804.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 31](https://user-images.githubusercontent.com/128868/57985922-b031ab80-7a23-11e9-958e-30118e6edc25.png)

**Espresso**
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 39](https://user-images.githubusercontent.com/128868/57985935-b758b980-7a23-11e9-9821-a6911d179c11.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 42](https://user-images.githubusercontent.com/128868/57985936-b758b980-7a23-11e9-9dc9-a3fd72ab8925.png)

**Cherry Mocha**
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 49](https://user-images.githubusercontent.com/128868/57985945-bd4e9a80-7a23-11e9-94b1-78eb0bddc54a.png)
![Simulator Screen Shot - iPhone Xʀ - 2019-05-19 at 10 47 52](https://user-images.githubusercontent.com/128868/57985946-bd4e9a80-7a23-11e9-8015-209337bfb9dc.png)

2019-05-19 22:44 UTC, rodericj commented
Oh noes. It conflicts. Maybe with keita’s latest.

2019-05-20 03:49 UTC, zadr commented
all fixed

2019-05-21 14:08 UTC, rodericj commented
I’ve not had a chance to look. But in the images have the fonts changed?

2019-05-22 03:03 UTC, zadr commented
yup, all unified in the style now.

everything support dynamic type now as well, which makes for a nice side effect

2019-05-22 05:48 UTC, rodericj commented on SF iOS/SF iOS/AppDelegate.m
> +- (void)setSharedNetworkCacheMemoryMegabytes:(NSInteger)memoryMiB diskMegabytes:(NSInteger)diskMiB {
very nice

2019-05-22 05:50 UTC, rodericj commented
We lost some shadows in the event feed unfortunately. Can we 🌮 bout that?

2019-05-22 05:52 UTC, rodericj commented
<img width="396" alt="Screen Shot 2019-05-21 at 10 51 26 PM" src="https://user-images.githubusercontent.com/75346/58150279-00bf2980-7c1b-11e9-9f79-446c99db8ce0.png">
Maybe this is just a style that's missing an attribute or something. I find it a bit hard to read.

2019-05-22 20:34 UTC, mcritz commented on SF iOS/SF iOS/AppDelegate.m
> +- (void)setSharedNetworkCacheMemoryMegabytes:(NSInteger)memoryMiB diskMegabytes:(NSInteger)diskMiB {
Broken. Put it back. /s

2019-05-22 20:37 UTC, mcritz commented
> We lost some shadows in the event feed unfortunately. Can we 🌮 bout that?

Must-fix

2019-05-22 23:13 UTC, rodericj commented on SF iOS/SF iOS/AppDelegate.m
> +- (void)setSharedNetworkCacheMemoryMegabytes:(NSInteger)memoryMiB diskMegabytes:(NSInteger)diskMiB {
Works perfectly

2019-05-22 23:14 UTC, rodericj requested changes
Looks like some UI got lost.

2019-05-24 05:08 UTC, zadr commented
> We lost some shadows in the event feed unfortunately. Can we 🌮 bout that?

fixed

2019-05-25 17:17 UTC, zadr commented
also changed the tint for the icons, lmk if anything else needs to be done here

2019-05-26 06:10 UTC, rodericj commented
Also yes this does in fact need to be rebased again :/

2019-05-27 05:00 UTC, rodericj commented
Let's do it. I made changes over in #127

2019-05-27 05:00 UTC, rodericj approved these changes

2019-05-27 05:01 UTC, merged